package com.royalrangers.enums;

public enum ImageType {
    USER_AVATAR,
    PLATOON_LOGO,
    TEST_LOGO,
    QUARTER_ACHIEVEMENT_LOGO,
    YEAR_ACHIEVEMENT_LOGO,
    THREE_YEAR_ACHIEVEMENT_LOGO,
    TWELVE_YEAR_ACHIEVEMENT_LOGO,
    REWARD_LOGO
}
