package com.royalrangers.enums;


public enum UserRank {
    /* For children*/
    SENIOR_LEADER,
    SENIOR_LEADER_ASSISTANT,
    LEADER,
    LEADER_ASSISTANT,
    STEWARD,
    SCRIBE,
    CHRONICLER,
    CHAPLAIN_ASSISTANT,
    COMMANDER_ASSISTANT,

    /*For adult*/
    ASSISTANT_COMMANDER,
    COMMANDER,
    SENIOR_COMMANDER,
    CHAPLAIN,
    PASTOR,
    PLATOON_COUNCILMAN,
    CITY_COMMANDER,
    CITY_STAFF_MEMBER,
    REGIONAL_COMMANDER,
    SECOND_REGIONAL_COMMANDER,
    REGIONAL_CHAPLAIN,
    REGIONAL_STAFF_MEMBER,
    ZONAL_COMMANDER,
    SECOND_ZONAL_COMMANDER,
    ZONAL_CHAPLAIN,
    ZONAL_STAFF_MEMBER,
    NATIONAL_COMMANDER,
    SECOND_NATIONAL_COMMANDER,
    NATIONAL_CHAPLAIN,
    NATIONAL_STAFF_MEMBER
}
